# Head Files

In [1]:
import torch
import torchvision
# from torch.utils.tensorboard import SummaryWriter
import time
from torch import nn
from torch.utils.data import DataLoader
from load_data import MyData  # self-made
from torchvision import transforms
from tqdm import tqdm_notebook as tqdm # View procedure
import os
import scipy.io
from random import random
import numpy as np
import gc
from torch.utils.tensorboard import SummaryWriter
from net_cnn_lstm1 import MyNetwork
from torchnlp.word_to_vector import GloVe
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

# 训练模型

## 设置超参数

In [2]:
BATCH_SIZE = 1
C,H,W = 1,1,2400
learn_rate = 0.0005
num_epochs = 50

## 设置随机种子

In [3]:
import random
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
manualSeed = 32
random.seed(manualSeed)
torch.manual_seed(manualSeed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(manualSeed)

## 设置优化器和损失函数

In [4]:
import torch.optim as optim
device = torch.device("cuda:0")
gc.collect()
torch.cuda.empty_cache()

# ==损失函数权重
# ======== 二分类HC/DOC
# 计算总样本数量
# condition1
# total_samples = 887 + 985 + 879
# condition2
# total_samples = 929 + 1029 + 886
# condition3
# total_samples = 887 + 975 + 879
# rest
total_samples = 852 + 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 887, total_samples / (985 + 879)]
# condition2
# weights = [total_samples / 929, total_samples / (1029 + 886)]
# condition3
weights = [total_samples / 852, total_samples / (1051 + 872)]

# ======== 二分类MCS/UWS
# 计算总样本数量
# condition1
# total_samples = 985 + 879
# condition2
# total_samples = 1029 + 886
# condition3
# total_samples = 975 + 879
# rest
# total_samples = 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 985, total_samples / 879]
# condition2
# weights = [total_samples / 1029, total_samples / 886]
# condition3
# weights = [total_samples / 975, total_samples / 879]
# condition3
# weights = [total_samples / 1051, total_samples / 872]
# 将权重转换为张量
weights_tensor = torch.tensor(weights, device=device)

# 定义交叉熵损失函数并设置权重
criterion = nn.CrossEntropyLoss(weight=weights_tensor)
# criterion = nn.CrossEntropyLoss()
criterion = criterion.to(device)

## Training

In [ ]:
def make_dataset(dataset,mode):
    # find the fold file
    count = 0
    for person in range(len(dataset)):
        filename = os.path.join(dataset.path, dataset.file_path[person])
        # extract the pure name of the file
        parts = filename.split("\\")
        file_name = parts[-1]
        name_without_extension = file_name.split(".")[0]
        # label or data
        file_last = name_without_extension.split("_")[-1]
        if file_last.isdigit(): # data
            # is this fold or not
            if int(file_last) == fold: # yes
                print(filename)
                count = count + 1
                data_map = torch.load(filename)
                # train or test
                if name_without_extension.split("_")[-2] == "train":
                    for i in range(data_map.size(0)):
                        train_data.append(data_map[i])
                elif name_without_extension.split("_")[-2] == "test":
                    for i in range(data_map.size(0)):
                        test_data.append(data_map[i])
                if count == 4:
                    del data_map
                    gc.collect()
                    torch.cuda.empty_cache() 
                    break
            else:   # not
                pass
        else: # label
            file_last = name_without_extension.split("_")[-4]
            file_mode = name_without_extension.split("_")[-2]
            if file_mode == mode.split("_")[-1]: # is this mode or not
                # is this fold or not
                if int(file_last) == fold: # yes
                    print(filename)
                    count = count + 1
                    data_map = torch.load(filename)
                    # train or test
                    if name_without_extension.split("_")[-5] == "train":
                        for i in range(data_map.size(0)):
                            train_label.append(data_map[i])
                    elif name_without_extension.split("_")[-5] == "test":
                        for i in range(data_map.size(0)):
                            test_label.append(data_map[i])
                    if count == 4:
                        del data_map
                        gc.collect()
                        torch.cuda.empty_cache() 
                        break
                else:   # not
                    pass
            else:
                pass
        del filename, parts, file_name, name_without_extension, file_last
        gc.collect()
        torch.cuda.empty_cache()    
# 定义LSTM超参数
input_size = 64  # 输入特征维度
hidden_size = 64  # 隐藏单元数量
num_layers = 2  # LSTM层数
output_size = 2  # 输出类别数量
# 创建模型实例
# model_list = ['', '_CNN', '_CNN_spa', '_CNN_spa_lstm']
# model_name = model_list[0]
# if model_name == model_list[0]: #  CascadeCept
#     from network_cnn_lstm import MyNetwork
# elif model_name == model_list[1]: #  CNN
#     from network_cnn_lstm_2 import MyNetwork
# elif model_name == model_list[2]: # CascadeCept_1
#     from network_cnn_lstm_3 import MyNetwork
# elif model_name == model_list[3]: # CascadeCept_2
#     from network_cnn_lstm_4 import MyNetwork
model_list = ['_1', '_2', '_3', '_4']
model_name = model_list[1]
if model_name == model_list[0]: #  CascadeCept
    from net_cnn_lstm1 import MyNetwork
elif model_name == model_list[1]: #  CascadeCept:
    from net_cnn_lstm2 import MyNetwork
model = MyNetwork(input_size, hidden_size, num_layers, output_size)
model = model.to(device)

# experimental dir: rest, conditionA, conditionB, conditionC
exper_dir = "rest"
root_dir = f"../data/eegmap_split/{exper_dir}"
# classification = "hc_doc"/doc or "mcs_uws"/uws
classification = "hc_doc"
# classification = "mcs_uws"
fold_num = 5
for fold in tqdm(range(5)):
    # train num folds
#     fold = 0 # 选择折数
    # -- prepare datasets
    train_data = []
    train_label = []
    test_data = []
    test_label = []
    
    if classification == "hc_doc":
        # ---- hc
        dataset = MyData(root_dir, "train", "hc") # hc
        make_dataset(dataset,classification)
        dataset = MyData(root_dir, "test", "hc") # hc
        make_dataset(dataset,classification)
    # ---- mcs
    dataset = MyData(root_dir, "train", "mcs") # mcs
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "mcs") # hc
    make_dataset(dataset,classification)
    # ---- uws
    dataset = MyData(root_dir, "train", "uws") # uws
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "uws") # hc
    make_dataset(dataset,classification)
    
    print(torch.stack(train_data).size())
    print(torch.stack(train_label).size())
    print(torch.stack(test_data).size())
    print(torch.stack(test_label).size())
    del dataset
    gc.collect()
    torch.cuda.empty_cache()  
    
    train_data = torch.stack(train_data)
    train_label = torch.stack(train_label)
    test_data = torch.stack(test_data)
    test_label = torch.stack(test_label)
    # train dataset
    train_td = TensorDataset(train_data, train_label)
    train_loader = DataLoader(train_td, batch_size = BATCH_SIZE, shuffle = True)
    # test dataset
    test_td = TensorDataset(test_data, test_label)
    test_loader = DataLoader(test_td, batch_size = BATCH_SIZE, shuffle = True)
    del train_data, train_label, test_data, test_label, train_td, test_td
    gc.collect()
    torch.cuda.empty_cache()
    
    # set model for each fold
    model = MyNetwork(input_size, hidden_size, num_layers, output_size)
    model = model.to(device)
    optimizer = optim.Adam(model.parameters(), lr = learn_rate)
    scheduler = optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 30, 50], gamma=0.2)
    # -- start training
    start_time = time.time()
    # train and test step records
    total_train_step = 0
    total_test_step = 0
    min_test_loss = 1000
    # add Tensorboard
    writer_train = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_train_{fold}")
    writer_valid = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_{fold}")
    writer_valid_acc = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_acc_{fold}")
    for i in tqdm(range(num_epochs)):  
        print(f"========= Epoch {i} Training =========")
        # train steps
        model.train()
        for data in train_loader:
            # x, y
            data_map, label=data
            data_map_reshaped = torch.reshape(data_map, (110, 1, 1, 2400))
            label_int = label.long()
            data_map_reshaped=data_map_reshaped.to(device)
            label_int=label_int.to(device)
            del data_map, label
            gc.collect()
            torch.cuda.empty_cache()
            # y_pred
            label_pred = model(data_map_reshaped)
            # Loss Computation and Optimization
            loss = criterion(label_pred,label_int)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            # draw tensorboard
            total_train_step = total_train_step + 1
            # print info
            if total_train_step % 1000 == 0:
                end_time = time.time()
                print(label_pred)
                print(f"Train time: {end_time - start_time}")
                print(f"Train steps: {total_train_step}, Loss: {loss.item()}")
            writer_train.add_scalar("train_loss",loss.item(),total_train_step)
            # Clear gpu
            del data, data_map_reshaped, label_int, label_pred, loss
            gc.collect()
            torch.cuda.empty_cache()
        
        # Evaluation and save the best model
        print(f"========= Epoch {i} Testing =========")
        model.eval()
        total_test_loss = 0
        test_count = 0
        total_test_acc = 0
        with torch.no_grad():
            for data in test_loader:
                test_count = test_count + 1
                # x, y
                data_map, label=data
                data_map_reshaped = torch.reshape(data_map, (110, 1, 1, 2400))
                label_int = label.long()
                data_map_reshaped = data_map_reshaped.to(device)
                label_int = label_int.to(device)
                del data_map, label
                gc.collect()
                torch.cuda.empty_cache()
                # y_pred
                label_pred_test = model(data_map_reshaped)
                loss = criterion(label_pred_test,label_int)
#                 print(label_pred_test)
                # accuracy 
                total_test_acc = total_test_acc + ((label_pred_test.argmax(1)) == label_int).sum()
                # draw tensorboad
                total_test_loss = total_test_loss + loss
                if test_count % 100 == 0:
                    print(f"Loss: {total_test_loss} Accuracy: {total_test_acc/test_count}")
                # Clear gpu
                del data_map_reshaped, label_int, label_pred_test, loss, data
                gc.collect()
                torch.cuda.empty_cache()
        print(f"Total Loss: {total_test_loss} Total Accuracy: {total_test_acc/test_count}")
        writer_valid.add_scalar("test_loss", total_test_loss, total_test_step)
        writer_valid_acc.add_scalar("test_acc", total_test_acc/test_count, total_test_step)
        total_test_step = total_test_step + 1
        print("..........Saving the model..........")
        torch.save(model.state_dict(),f"../models/{classification}/{exper_dir}{model_name}/Fold{fold}_Epoch{i}.pt") 
#         if total_test_loss < min_test_loss:
#             min_test_loss = total_test_loss
#             print("..........Saving the model..........")
#             torch.save(model.state_dict(),f"../model/{exper_dir}/Fold{fold}_Epoch{i}.pt")

D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:92: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/5 [00:00<?, ?it/s]

../data/eegmap_split/rest\train\hc\rest_hc_train_0.pt
../data/eegmap_split/rest\train\hc\rest_hc_train_0_hc_doc_label.pt
../data/eegmap_split/rest\test\hc\rest_hc_test_0.pt
../data/eegmap_split/rest\test\hc\rest_hc_test_0_hc_doc_label.pt
../data/eegmap_split/rest\train\mcs\rest_mcs_train_0.pt
../data/eegmap_split/rest\train\mcs\rest_mcs_train_0_hc_doc_label.pt
../data/eegmap_split/rest\test\mcs\rest_mcs_test_0.pt
../data/eegmap_split/rest\test\mcs\rest_mcs_test_0_hc_doc_label.pt
../data/eegmap_split/rest\train\uws\rest_uws_train_0.pt
../data/eegmap_split/rest\train\uws\rest_uws_train_0_hc_doc_label.pt
../data/eegmap_split/rest\test\uws\rest_uws_test_0.pt
../data/eegmap_split/rest\test\uws\rest_uws_test_0_hc_doc_label.pt
torch.Size([2221, 2400, 10, 11])
torch.Size([2221])
torch.Size([554, 2400, 10, 11])
torch.Size([554])


D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:155: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/50 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-1.0312,  1.3408]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 140.9120659828186
Train steps: 1000, Loss: 0.08919516950845718
tensor([[ 0.1603, -0.0431]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 313.1831374168396
Train steps: 2000, Loss: 0.5966081619262695
========= Epoch 0 Testing =========
Loss: 22.199527740478516 Accuracy: 0.9399999976158142
Loss: 46.68478775024414 Accuracy: 0.9199999570846558
Loss: 67.2136459350586 Accuracy: 0.9233333468437195
Loss: 93.64163208007812 Accuracy: 0.9274999499320984
Loss: 118.77064514160156 Accuracy: 0.9280000329017639
Total Loss: 131.95175170898438 Total Accuracy: 0.9259927868843079
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[-1.7635,  2.2439]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 542.4551753997803
Train steps: 3000, Loss: 0.018016966059803963
tensor([[-3.0734,  3.7505]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train ti

Loss: 6.112487316131592 Accuracy: 0.9950000047683716
Loss: 6.332467555999756 Accuracy: 0.9960000514984131
Total Loss: 6.75209903717041 Total Accuracy: 0.9963898658752441
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[-5.0235,  5.7089]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4863.0342609882355
Train steps: 25000, Loss: 2.1815061700181104e-05
tensor([[-5.3736,  6.0541]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5035.123284101486
Train steps: 26000, Loss: 1.0847985322470777e-05
========= Epoch 11 Testing =========
Loss: 0.4532122015953064 Accuracy: 1.0
Loss: 1.5076662302017212 Accuracy: 0.9950000047683716
Loss: 1.8661847114562988 Accuracy: 0.996666669845581
Loss: 2.5248241424560547 Accuracy: 0.9975000023841858
Loss: 2.746464729309082 Accuracy: 0.9980000257492065
Total Loss: 5.948395729064941 Total Accuracy: 0.994584858417511
..........Saving the model..........
========= Epoch 12 Training =========
tensor([[-5.4359,  6.09

Total Loss: 9.227363586425781 Total Accuracy: 0.994584858417511
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[ 12.0360, -11.3639]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9720.852806806564
Train steps: 49000, Loss: 0.0
tensor([[-12.1604,  10.0951]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9889.228067159653
Train steps: 50000, Loss: 0.0
tensor([[-12.5055,  10.2696]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10062.129089355469
Train steps: 51000, Loss: 0.0
========= Epoch 22 Testing =========
Loss: 4.858819961547852 Accuracy: 0.9799999594688416
Loss: 13.75762939453125 Accuracy: 0.9799999594688416
Loss: 16.631973266601562 Accuracy: 0.9833333492279053
Loss: 16.66209602355957 Accuracy: 0.9874999523162842
Loss: 21.513208389282227 Accuracy: 0.9860000610351562
Total Loss: 22.380952835083008 Total Accuracy: 0.9873645901679993
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-12.

tensor([[-14.3505,  10.7502]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14610.01467347145
Train steps: 74000, Loss: 0.0
tensor([[ 13.5602, -11.8467]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14781.77178144455
Train steps: 75000, Loss: 0.0
========= Epoch 33 Testing =========
Loss: 8.562386512756348 Accuracy: 0.9799999594688416
Loss: 10.49254322052002 Accuracy: 0.98499995470047
Loss: 11.287473678588867 Accuracy: 0.9900000095367432
Loss: 11.29053783416748 Accuracy: 0.9925000071525574
Loss: 11.449031829833984 Accuracy: 0.9940000176429749
Total Loss: 11.943548202514648 Total Accuracy: 0.994584858417511
..........Saving the model..........
========= Epoch 34 Training =========
tensor([[-14.3855,  10.7712]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15005.064890623093
Train steps: 76000, Loss: 0.0
tensor([[ 14.3318, -12.4044]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15173.866904258728
Train steps: 77000, Loss: 0.0
========= Epoch 34 T

========= Epoch 44 Testing =========
Loss: 0.009399889037013054 Accuracy: 1.0
Loss: 4.1199116706848145 Accuracy: 0.9950000047683716
Loss: 4.320067882537842 Accuracy: 0.996666669845581
Loss: 4.654809951782227 Accuracy: 0.9975000023841858
Loss: 5.741105556488037 Accuracy: 0.9960000514984131
Total Loss: 16.381940841674805 Total Accuracy: 0.9927797913551331
..........Saving the model..........
========= Epoch 45 Training =========
tensor([[ 14.7161, -12.5553]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19702.055606365204
Train steps: 100000, Loss: 0.0
tensor([[-15.0463,  11.0770]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19871.245606660843
Train steps: 101000, Loss: 0.0
tensor([[-15.1436,  11.1269]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20042.89262986183
Train steps: 102000, Loss: 0.0
========= Epoch 45 Testing =========
Loss: 4.937437534332275 Accuracy: 0.9699999690055847
Loss: 5.146876811981201 Accuracy: 0.98499995470047
Loss: 5.1496562957763

  0%|          | 0/50 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.1197,  0.2672]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 165.2890100479126
Train steps: 1000, Loss: 0.9051798582077026
tensor([[ 0.8071, -0.6066]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 334.43902349472046
Train steps: 2000, Loss: 0.21772290766239166
========= Epoch 0 Testing =========
Loss: 36.67147445678711 Accuracy: 0.8499999642372131
Loss: 65.91032409667969 Accuracy: 0.8799999952316284
Loss: 105.21404266357422 Accuracy: 0.8666666746139526
Loss: 134.6295928955078 Accuracy: 0.875
Loss: 171.3842315673828 Accuracy: 0.8740000128746033
Total Loss: 190.6723175048828 Total Accuracy: 0.8718411326408386
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[ 2.1944, -1.6500]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 558.9560577869415
Train steps: 3000, Loss: 0.02117222547531128
tensor([[-3.6671,  3.0710]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 723.131125

Loss: 31.067419052124023 Accuracy: 0.9724999666213989
Loss: 40.16426467895508 Accuracy: 0.9720000624656677
Total Loss: 45.83323669433594 Total Accuracy: 0.9711191058158875
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[ 3.6485, -2.9537]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4671.830051898956
Train steps: 25000, Loss: 0.0013565156841650605
tensor([[-4.8545,  4.2512]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4834.46794629097
Train steps: 26000, Loss: 0.00011097768583567813
========= Epoch 11 Testing =========
Loss: 4.459795951843262 Accuracy: 0.9799999594688416
Loss: 9.470490455627441 Accuracy: 0.98499995470047
Loss: 17.225360870361328 Accuracy: 0.9733333587646484
Loss: 22.865041732788086 Accuracy: 0.9724999666213989
Loss: 26.49285316467285 Accuracy: 0.9780000448226929
Total Loss: 27.28295135498047 Total Accuracy: 0.9801443815231323
..........Saving the model..........
========= Epoch 12 Training =========
tensor([[-3

========= Epoch 21 Testing =========
Loss: 9.024211883544922 Accuracy: 0.9899999499320984
Loss: 19.17906951904297 Accuracy: 0.9899999499320984
Loss: 21.038801193237305 Accuracy: 0.9900000095367432
Loss: 21.184450149536133 Accuracy: 0.9925000071525574
Loss: 41.401485443115234 Accuracy: 0.9880000352859497
Total Loss: 52.8385009765625 Total Accuracy: 0.9873645901679993
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[ 8.3614, -7.3053]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9153.915636777878
Train steps: 49000, Loss: 1.1920928244535389e-07
tensor([[ 8.9130, -7.8252]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9312.366923093796
Train steps: 50000, Loss: 0.0
tensor([[-9.1802,  8.1664]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9474.809099197388
Train steps: 51000, Loss: 0.0
========= Epoch 22 Testing =========
Loss: 14.18649959564209 Accuracy: 0.9799999594688416
Loss: 14.564733505249023 Accuracy: 0.98999994993209

========= Epoch 32 Testing =========
Loss: 11.104019165039062 Accuracy: 0.9899999499320984
Loss: 40.5345458984375 Accuracy: 0.98499995470047
Loss: 40.56801223754883 Accuracy: 0.9900000095367432
Loss: 62.223289489746094 Accuracy: 0.9874999523162842
Loss: 63.40369415283203 Accuracy: 0.9880000352859497
Total Loss: 63.403717041015625 Total Accuracy: 0.9891696572303772
..........Saving the model..........
========= Epoch 33 Training =========
tensor([[-13.3138,  11.3101]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13808.105488300323
Train steps: 74000, Loss: 0.0
tensor([[ 12.3925, -11.0803]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13970.577353954315
Train steps: 75000, Loss: 0.0
========= Epoch 33 Testing =========
Loss: 15.898731231689453 Accuracy: 0.9899999499320984
Loss: 23.112747192382812 Accuracy: 0.9899999499320984
Loss: 27.85173797607422 Accuracy: 0.9900000095367432
Loss: 37.666202545166016 Accuracy: 0.9874999523162842
Loss: 37.68293762207031 Accuracy: 0.

Loss: 26.49220848083496 Accuracy: 0.9900000095367432
Loss: 52.4065055847168 Accuracy: 0.9874999523162842
Loss: 52.406517028808594 Accuracy: 0.9900000691413879
Total Loss: 69.49591064453125 Total Accuracy: 0.9891696572303772
..........Saving the model..........
========= Epoch 44 Training =========
tensor([[-13.4487,  11.3438]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18304.179348230362
Train steps: 98000, Loss: 0.0
tensor([[-14.4145,  12.1728]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18465.84632730484
Train steps: 99000, Loss: 0.0
========= Epoch 44 Testing =========
Loss: 1.7380486726760864 Accuracy: 0.9899999499320984
Loss: 13.700901985168457 Accuracy: 0.9899999499320984
Loss: 13.701263427734375 Accuracy: 0.9933333396911621
Loss: 27.359825134277344 Accuracy: 0.9925000071525574
Loss: 27.359920501708984 Accuracy: 0.9940000176429749
Total Loss: 34.97239303588867 Total Accuracy: 0.9909747242927551
..........Saving the model..........
========= Epoch 45 Trai

  0%|          | 0/50 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-1.7501,  1.7018]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 160.59459686279297
Train steps: 1000, Loss: 0.03119569458067417
tensor([[ 1.3347, -1.0719]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 323.00373363494873
Train steps: 2000, Loss: 0.08628665655851364
========= Epoch 0 Testing =========
Loss: 23.18178939819336 Accuracy: 0.9099999666213989
Loss: 64.87535858154297 Accuracy: 0.8549999594688416
Loss: 91.27991485595703 Accuracy: 0.8633333444595337
Loss: 114.59626770019531 Accuracy: 0.8774999976158142
Loss: 142.9735870361328 Accuracy: 0.8840000629425049
Total Loss: 160.13674926757812 Total Accuracy: 0.8826714754104614
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[-1.3422,  1.2094]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 539.3039364814758
Train steps: 3000, Loss: 2.626657485961914
tensor([[-2.5174,  2.2293]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train ti

Loss: 38.64500427246094 Accuracy: 0.9524999856948853
Loss: 47.03499984741211 Accuracy: 0.9540000557899475
Total Loss: 49.918724060058594 Total Accuracy: 0.9566786885261536
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[ 6.1998, -5.1699]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4673.470755338669
Train steps: 25000, Loss: 1.156323378381785e-05
tensor([[-7.8275,  7.0121]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4835.745738267899
Train steps: 26000, Loss: 3.576278118089249e-07
========= Epoch 11 Testing =========
Loss: 10.084009170532227 Accuracy: 0.949999988079071
Loss: 15.531418800354004 Accuracy: 0.9599999785423279
Loss: 26.88503074645996 Accuracy: 0.9533333778381348
Loss: 30.579931259155273 Accuracy: 0.9599999785423279
Loss: 38.651397705078125 Accuracy: 0.9580000638961792
Total Loss: 48.97702407836914 Total Accuracy: 0.9548736214637756
..........Saving the model..........
========= Epoch 12 Training =========
tensor([

tensor([[-12.7289,   9.9025]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9174.194756269455
Train steps: 49000, Loss: 0.0
tensor([[-13.1274,  10.2587]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9337.017404556274
Train steps: 50000, Loss: 0.0
tensor([[ 13.4534, -10.8999]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9499.084894657135
Train steps: 51000, Loss: 0.0
========= Epoch 22 Testing =========
Loss: 2.2559330463409424 Accuracy: 0.9899999499320984
Loss: 2.2578418254852295 Accuracy: 0.9950000047683716
Loss: 2.2617697715759277 Accuracy: 0.996666669845581
Loss: 2.3634235858917236 Accuracy: 0.9975000023841858
Loss: 2.3815338611602783 Accuracy: 0.9980000257492065
Total Loss: 2.399144172668457 Total Accuracy: 0.9981949329376221
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-13.9522,  10.8077]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9715.644127368927
Train steps: 52000, Loss: 0.0
tensor([[-13.6249,

tensor([[ 13.3345, -10.8071]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14023.629578590393
Train steps: 75000, Loss: 0.0
========= Epoch 33 Testing =========
Loss: 1.4915133714675903 Accuracy: 0.9899999499320984
Loss: 3.6055474281311035 Accuracy: 0.98499995470047
Loss: 14.868083953857422 Accuracy: 0.9800000190734863
Loss: 27.40911102294922 Accuracy: 0.9774999618530273
Loss: 31.969669342041016 Accuracy: 0.9800000190734863
Total Loss: 31.994733810424805 Total Accuracy: 0.9819494485855103
..........Saving the model..........
========= Epoch 34 Training =========
tensor([[-14.5900,  11.1437]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14240.972435235977
Train steps: 76000, Loss: 0.0
tensor([[ 14.1400, -11.3810]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14403.799523830414
Train steps: 77000, Loss: 0.0
========= Epoch 34 Testing =========
Loss: 4.994842052459717 Accuracy: 0.9799999594688416
Loss: 9.504413604736328 Accuracy: 0.9799999594688416
Loss: 1

========= Epoch 44 Testing =========
Loss: 0.004813334438949823 Accuracy: 1.0
Loss: 0.009251981973648071 Accuracy: 1.0
Loss: 0.07058294862508774 Accuracy: 1.0
Loss: 0.07082207500934601 Accuracy: 1.0
Loss: 0.09392115473747253 Accuracy: 1.0
Total Loss: 1.6190319061279297 Total Accuracy: 0.9981949329376221
..........Saving the model..........
========= Epoch 45 Training =========
tensor([[-14.9745,  11.5138]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18750.989167928696
Train steps: 100000, Loss: 0.0
tensor([[-14.2477,  10.8706]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18914.57305574417
Train steps: 101000, Loss: 0.0
tensor([[-14.9231,  11.4221]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19077.23112845421
Train steps: 102000, Loss: 0.0
========= Epoch 45 Testing =========
Loss: 45.12818145751953 Accuracy: 0.9300000071525574
Loss: 128.7610321044922 Accuracy: 0.9199999570846558
Loss: 159.46432495117188 Accuracy: 0.9266666769981384
Loss: 219.3265075

  0%|          | 0/50 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.9000,  0.9428]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 160.10561537742615
Train steps: 1000, Loss: 0.14701777696609497
tensor([[-1.2799,  1.3569]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 322.3889183998108
Train steps: 2000, Loss: 0.06914069503545761
========= Epoch 0 Testing =========
Loss: 37.95658874511719 Accuracy: 0.8700000047683716
Loss: 72.67112731933594 Accuracy: 0.8700000047683716
Loss: 100.08179473876953 Accuracy: 0.8700000047683716
Loss: 156.12167358398438 Accuracy: 0.8524999618530273
Loss: 190.82017517089844 Accuracy: 0.8560000658035278
Total Loss: 209.2842254638672 Total Accuracy: 0.8574007153511047
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[-2.5486,  2.5836]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 549.6409928798676
Train steps: 3000, Loss: 0.005886124912649393
tensor([[-0.0215, -0.0177]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train

Loss: 21.31199073791504 Accuracy: 0.9824999570846558
Loss: 34.128501892089844 Accuracy: 0.9740000367164612
Total Loss: 40.025611877441406 Total Accuracy: 0.9729241728782654
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[ 3.6772, -3.7718]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3299.878484725952
Train steps: 25000, Loss: 0.0005818104837089777
tensor([[-2.1631,  2.3989]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3392.4899187088013
Train steps: 26000, Loss: 0.010386461392045021
========= Epoch 11 Testing =========
Loss: 5.908524990081787 Accuracy: 0.9799999594688416
Loss: 14.150157928466797 Accuracy: 0.9649999737739563
Loss: 21.831331253051758 Accuracy: 0.9633333683013916
Loss: 43.45424270629883 Accuracy: 0.9524999856948853
Loss: 57.09932327270508 Accuracy: 0.9440000653266907
Total Loss: 60.79727554321289 Total Accuracy: 0.9458483457565308
..........Saving the model..........
========= Epoch 12 Training =========
tensor([

Loss: 15.17070198059082 Accuracy: 0.9899999499320984
Loss: 46.92131042480469 Accuracy: 0.9699999690055847
Loss: 61.476226806640625 Accuracy: 0.9733333587646484
Loss: 106.34644317626953 Accuracy: 0.9699999690055847
Loss: 130.956298828125 Accuracy: 0.9720000624656677
Total Loss: 130.9609375 Total Accuracy: 0.9747292399406433
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[-10.3987,   9.2855]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6165.712842464447
Train steps: 49000, Loss: 0.0
tensor([[-10.7970,   9.5500]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6322.699383735657
Train steps: 50000, Loss: 0.0
tensor([[-11.0564,   9.6845]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6478.04647898674
Train steps: 51000, Loss: 0.0
========= Epoch 22 Testing =========
Loss: 23.283926010131836 Accuracy: 0.9599999785423279
Loss: 68.92411041259766 Accuracy: 0.9599999785423279
Loss: 69.84127807617188 Accuracy: 0.9700000286102295
Lo

In [7]:
for i in range(1,5):
    print(i)

1
2
3
4
